####################################
# NetworkPolicy for reivews service which denies all egress except to:
#    - all pods in kube-system (dns required)
#    - all pods in istio-system ( required)
#    - all pods in the ratings service
####################################
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: reviews-egress
  labels:
    app: {{ .Values.BookInfoLabel }}
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kube-system: ns
  - to:
    - namespaceSelector:
        matchLabels:
          istio-system: ns
  - to:
    - podSelector:
        matchLabels:
          app: ratings
  podSelector:
    matchLabels:
      app: reviews
  policyTypes:
  - Egress