###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: prism.actions.ingress
  namespace: prism
  labels:
data:
  url-actions: |
    [
      { 
        "name":"detail", 
        "text":"Ingress detail", 
        "description":"Ingress detail", 
{{ if eq .Values.env.kubeEnv "minikube" }}
        "url-pattern":"${builtin.icp-console-url}/ingress/${resource.$.metadata.namespace}/${resource.$.metadata.name}?namespace=${resource.$.metadata.namespace}", 
{{ else }}
        "url-pattern":"${builtin.icp-console-url}/access/services/ingress/${resource.$.metadata.namespace}/${resource.$.metadata.name}", 
{{ end }}
        "open-window": "current", 
        "menu-item": "false" 
      }
    ]
