###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion:  v1
kind: ConfigMap
metadata: 
  name: prism.actions.websphere-traditional
  namespace: prism
  labels:
data:
  url-actions: | 
      [
        {  
          "name": "details", 
          "text":"details",
          "description": "View twas details", 
          "url-pattern": "https://${builtin.icp-console-url}/prism/was_nd_app/${resource.$.metadata.namespace}/${resource.$['metadata']['name']}",
          "open-window": "current",
          "menu-item": "false" 
        },
        {  
          "name": "dmgr", 
          "text": "Manage application",
          "description": "Login to Deployment manager", 
          "url-pattern": "${resource.$.metadata.annotations['prism.platform.console-url']}",
          "open-window": "tab"
        },
        {  
          "name": "logs", 
          "text": "View Kibana Logs",
          "description": "View Kibana logs", 
          "url-pattern": "https://${builtin.kibana-url}/${builtin.liberty-log-dashboard}",
          "open-window": "tab"
        }
      ] 
