###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion:  v1
kind: ConfigMap
metadata: 
  name: prism.actions.websphere-liberty
  namespace: prism
  labels:
data:
  url-actions: | 
      [
        {  
          "name": "config", 
          "text": "Manage Application",
          "description": "Login to admin center", 
          "url-pattern": "${resource.$.metadata.annotations['prism.platform.console-url']}",
          "open-window": "tab"
        },
        {  
          "name": "logs", 
          "text": "View Kibana Logs",
          "description": "View Kibana logs", 
          "url-pattern": "https://${builtin.kibana-url}/${builtin.liberty-log-dashboard}",
          "open-window": "tab"
        }
      ] 
