###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: prism.actions.deployment-node.js
  namespace: prism
data:
  url-actions: |
    [
      {
        "name":"monitor",
        "text":"View AppMetrics Dash",
        "description":"Open AppMetrics Dashboard",
        "url-pattern": "http://9.42.26.48:${func.kubectlGet(service,${resource.$.metadata.name}-service,--namespace,${resource.$.metadata.namespace},-o,jsonpath=${snippet.nodeport()})}/appmetrics-dash",
        "open-window": "tab"
      }
    ]
  snippets: |
    {
      "nodeport": "function nodeport() {
        return '{.spec.ports[0].nodePort}'
      }"
     }
