###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
image:
  __metadata:
    label: "Image"
    description: "Image"
  repository:
    __metadata:
      name: "repository"
      label: "Repository"
      description: "Docker image location"
      type: "string"
      immutable: false
      required: true
  repositoryUI:
    __metadata:
      name: "repositoryUI"
      label: "Repository UI"
      description: "Docker image location for UI"
      type: "string"
      immutable: false
      required: true
  repositoryInit:
    __metadata:
      name: "repositoryInit"
      label: "Repository Init"
      description: "Docker image location for init"
      type: "string"
      immutable: false
      required: true
  tag:
    __metadata:
      name: "tag"
      label: "Tag"
      description: "Docker image tag"
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Defaults to 'Always' when the latest tag is specified. Otherwise the default is 'IfNotPresent'."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent"

# Service
service:
  __metadata:
    label: "Service"
    description: "Service"
  type:
    __metadata:
      name: "type"
      label: "Service Type"
      description: "Type of service"
      type: "string"
      immutable: false
      required: true
      options:
        - label: "Cluster IP"
          value: "ClusterIP"
        - label: "Node Port"
          value: "NodePort"
  name:
    __metadata:
      name: "name"
      label: "Name"
      description: "The name of the service."
      type: "string"
      immutable: false
      required: false
  port:
    __metadata:
      name: "port"
      label: "HTTP Port"
      description: "The HTTP port that the container will expose."
      type: "number"
      immutable: false
      required: true
  targetPort:
    __metadata:
      name: "targetPort"
      label: "HTTP Target port"
      description: "A service can map an incoming HTTP port to the targetPort."
      type: "string"
      immutable: false
      required: true
  scheme:
    __metadata:
      name: "scheme"
      label: "Scheme"
      description: "HTTP or HTTPS"
      type: "string"
      immutable: false
      required: true

## Environmental Variables
env:
  __metadata:
    label: "Environmental Variables"
    description: "Environmental Variables"
  jvmArgs:
    __metadata:
      name: "jvmArgs"
      label: "JVM_ARGS"
      description: "Liberty runtime JVM arguments."
      type: "string"
      immutable: false
      hidden: true
      required: false
  kubeEnv:
    __metadata:
      name: "kubeEnv"
      label: "Kubernetes Environment"
      description: "Kubernetes Environment."
      type: "string"
      immutable: false
      hidden: true
      required: false
  target:
    __metadata:
      name: "target"
      label: "Target"
      description: "API server target."
      type: "string"
      immutable: false
      required: true

# Logs
logs:
  __metadata:
    label: "Logs"
    description: "Logs"
  consoleFormat:      
    __metadata:
      name: "consoleFormat"
      label: "Console logging format"
      description: "Specifies container log output format."
      type: "string"
      immutable: false
      hidden: true
      required: true
      options:
      - label: "json"
        value: "json"
      - label: "basic"
        value: "basic"
  consoleLogLevel:      
    __metadata:
      name: "consoleLogLevel"
      label: "Console logging level"
      description: "Controls the granularity of messages that go to the container log."
      type: "string"
      immutable: false
      hidden: true
      required: true
      options:
      - label: "info"
        value: "info"
      - label: "audit"
        value: "audit"
      - label: "warning"
        value: "warning"
      - label: "error"
        value: "error"
      - label: "off"
        value: "off"
  consoleSource:      
    __metadata:
      name: "consoleSource"
      label: "Console logging sources"
      description: "Specify sources that are written to the container log. Use a comma separated list for multiple sources."
      type: "string"
      immutable: false
      hidden: true
      required: true

microprofile:
  __metadata:
    label: "MicroProfile settings"
    description: "MicroProfile settings"
  health:
    enabled:
      __metadata:
        name: "health.enabled"
        label: "Enable health"
        description: "Specifies whether to use the MicroProfile health endpoint (`/health`) as a readiness probe of the container. Requires HTTP service to be enabled."
        type: "boolean"
        immutable: false
        hidden: true
        required: true

monitoring:
  __metadata:
    label: "Monitoring"
    description: "Monitoring"
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable monitoring"
      description: "Specifies whether to use Liberty features `monitor-1.0` and `mpMetrics-1.1` to monitor the server runtime environment and application metrics. Requires HTTP service to be enabled."
      type: "boolean"
      immutable: false
      hidden: true
      required: true

replicaCount:
  __metadata:
    name: "replicaCount"
    label: "Number of replicas"
    description: "The number of desired replica pods that run simultaneously."
    type: "number"
    immutable: false
    hidden: true
    required: true

autoscaling:
  __metadata:
    label: "Automatically scale pods"
    description: "Automatically scale pods"
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable automatic scaling"
      description: "Specifies whether a horizontal pod autoscaler (HPA) is deployed. Note that enabling this field disables the Number of replicas field."
      type: "boolean"
      immutable: false
      hidden: true
      required: true
  targetCPUUtilizationPercentage:
    __metadata:
      name: "targetCPUUtilizationPercentage"
      label: "Target CPU utilization percentage"
      description: "Target average CPU utilization (represented as a percentage of requested CPU) over all the pods."
      type: "number"
      immutable: false
      hidden: true
      required: true
  minReplicas:
    __metadata:
      name: "minReplicas"
      label: "Minimum number of replicas"
      description: "Lower limit for the number of pods that can be set by the autoscaler."
      type: "number"
      immutable: false
      hidden: true
      required: true
  maxReplicas:
    __metadata:
      name: "maxReplicas"
      label: "Maximum number of replicas"
      description: "Upper limit for the number of pods that can be set by the autoscaler.  Cannot be lower than the minimum number of replicas."
      type: "number"
      immutable: false
      hidden: true
      required: true

resources:
  __metadata:
    label: "Resources"
    description: "Resources"
  constraints:
    enabled:
      __metadata:
        name: "constraints.enabled"
        label: "Enable constraints"
        description: "Specifies whether the resource constraints in this Helm chart are enabled."
        type: "boolean"
        immutable: false
        hidden: true
        required: true
  limits:
    cpu:
      __metadata:
        name: "limits.cpu"
        label: "Maximum CPU"
        description: "Describes the maximum amount of CPU allowed."
        type: "string"
        immutable: false
        hidden: true
        required: false
    memory:
      __metadata:
        name: "limits.memory"
        label: "Maximum memory"
        description: "Describes the maximum amount of memory allowed."
        type: "string"
        immutable: false
        hidden: true
        required: false
  requests:
    cpu:
      __metadata:
        name: "requests.cpu"
        label: "Minimum CPU"
        description: "Describes the minimum amount of CPU required. Corresponds to requests.cpu in Kubernetes. If not specified it will default to maximum CPU (if specified) or otherwise implementation-defined value."
        type: "string"
        immutable: false
        hidden: true
        required: false
    memory:
      __metadata:
        name: "requests.memory"
        label: "Minimum memory"
        description: "Describes the minimum amount of memory required. Corresponds to requests.memory in Kubernetes. If not specified it will default to maximum memory (if specified) or otherwise implementation-defined value."
        type: "string"
        immutable: false
        hidden: true
        required: false

## Arch metadata
arch:
  __metadata:
    label: "Architecture scheduling preferences"
    description: "Architecture scheduling preferences"
    hidden: true
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64 scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      hidden: true
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "ppc64le scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      hidden: true
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

  s390x:
    __metadata:
      name: "s390x"
      label: "s390x scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      hidden: true
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No preference"
        value: "2 - No preference"
      - label: "3 - Most preferred"
        value: "3 - Most preferred"

## Role-Based Access Control
rbac:
  __metadata:
    label: "RBAC roles and bindings"
    description: "RBAC roles and bindings"
    hidden: true
  install:
    __metadata:
      name: "install"
      label: "Install"
      description: "Install RBAC roles and bindings"
      type: "boolean"
      immutable: false
      hidden: true
      required: true
