###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2019. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################


###############################################################################
## Common image variables
###############################################################################
image:
  repository: ibmcom/app-nav-api
  repositoryUI: ibmcom/app-nav-ui
  repositoryInit: ibmcom/app-nav-init
  tag: latest
  pullPolicy: Always

service:
  name: ""
  port: 9443
  targetPort: 9443
  type: NodePort
  scheme: HTTPS
  openAPI: disabled

###############################################################################
## Environmental variables
###############################################################################
env:
  jvmArgs: ""
  kubeEnv: icp
  target: "https://localhost:9443"

###############################################################################
## Logs
###############################################################################
logs:
  consoleFormat: json
  consoleLogLevel: info
  consoleSource: message,trace,accessLog,ffdc

###############################################################################
## MicroProfile
###############################################################################
microprofile:
  health: 
    enabled: false

###############################################################################
## Monitoring
###############################################################################
monitoring:
  enabled: false

###############################################################################
## Auto scaling
###############################################################################
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  
###############################################################################
## Resource constraints
###############################################################################
resources:
  constraints: 
    enabled: false
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

###############################################################################
## Architecture
###############################################################################
# Specify architecture (amd64, ppc64le, s390x) and weight to be
# used for scheduling as follows : 
#   0 - Do not use
#   1 - Least preferred
#   2 - No preference
#   3 - Most preferred
arch:
  amd64: "3 - Most preferred"
  ppc64le: "0 - Do not use"
  s390x: "0 - Do not use"

###############################################################################
## Role-Based Access Control
###############################################################################
rbac:
  install: true
